package soap_corba;


/**
* soap_corba/NotificacionesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* miércoles 9 de diciembre de 2020 12:12:31 AM COT
*/

abstract public class NotificacionesHelper
{
  private static String  _id = "IDL:soap_corba/Notificaciones:1.0";

  public static void insert (org.omg.CORBA.Any a, soap_corba.Notificaciones that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static soap_corba.Notificaciones extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (soap_corba.NotificacionesHelper.id (), "Notificaciones");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static soap_corba.Notificaciones read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NotificacionesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, soap_corba.Notificaciones value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static soap_corba.Notificaciones narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof soap_corba.Notificaciones)
      return (soap_corba.Notificaciones)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      soap_corba._NotificacionesStub stub = new soap_corba._NotificacionesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static soap_corba.Notificaciones unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof soap_corba.Notificaciones)
      return (soap_corba.Notificaciones)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      soap_corba._NotificacionesStub stub = new soap_corba._NotificacionesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
