package soap_corba;


/**
* soap_corba/Notificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* miércoles 9 de diciembre de 2020 12:12:31 AM COT
*/

public interface Notificaciones extends NotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Notificaciones
